<?php

function dna_menu() {
    $items = array();
    $items['dna'] = array(
        'title' => 'DNA Match',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_match_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );
    $items['dna_match_results_page'] = array(
        'title' => 'Results',
        'page callback' => 'dna_match_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_match_form() {
    $form['nucleotides'] = array(
        '#title' => 'Nucleotides',
        '#description' => t('Enter in a string that only contains the combination of letters "A", "C", "G" or "T" without spaces to find your matching nucleotide sequence.'),
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_input'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit!'),
    );
    return $form;
}

function element_validate_input($element) {
    $bases = array('A', 'C', 'T', 'G');
    $input = str_split(strtoupper($element['#value']));
    foreach($input as $base) {
        if ($base == "U") {
            form_error($element, t("You're thinking of RNA! In an RNA strand, Uracil replaces the spot of Thymine. Take out the 'U' and enter in any combination of 'A', 'C', 'T', or 'G'."));
        }
        else if (!in_array($base, $bases)) {
            form_error($element, t('Please enter in a string that only contains any combination of "A", "G", "T", "C".'));
        }
    }
}

function find_match($input) {
    $bases = str_split(strtoupper($input));
    $output = array();

    foreach($bases as $base) {
        if ($base == "A") {
            array_push($output, 'T');
        } else if ($base == 'T') {
            array_push($output, 'A');
        } else if ($base == 'C') {
            array_push($output, 'G');
        } else if ($base == 'G') {
            array_push($output, 'C');
        }
    }
    $output = implode('', $output);
    return $output;
}

function dna_match_form_submit($form, &$form_state) {
    $input = $form_state['values']['nucleotides'];
    $output = find_match($input);
    $_SESSION['input'] = strtoupper($input);
    $_SESSION['output'] = $output;
    $form_state['redirect'] = 'dna_match_results_page';
}

function dna_match_results() {
    return '<p>You entered in the base ' . $_SESSION['input'] . '.</p>
            <p>Your matching nucleotide sequence is ' . $_SESSION['output'] . '.</p>';
}
